version: "2.1"
services:
  librespeed:
    image: linuxserver/librespeed:latest
    container_name: librespeed
    ports:
      - 5005:80
    environment:
      - PUID=1001
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/config
    restart: always