version: "2.1"
services:
  calibre-web:
    image: johngong/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - CALIBRE_ASCII_FILENAME=false
      - ENABLE_CALIBRE_SERVER_OPDS=true
      - ENABLE_DOUBAN_SEARCH=true
    volumes:
      - ./data:/config
      - ./book/.library:/library
      - ./book/添加书籍:/autoaddbooks
    ports:
      - 8083:8083
      - 8080:8080
