version: "2.1"
services:
  jellyfin:
    image: nyanmisaka/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/config
      - ./media:/media
    devices:
      - /dev/dri:/dev/dri #optional
    restart: unless-stopped
    network_mode: "host"
