version: "3.9"
services:
  alist:
    image: xhofe/alist:latest
    container_name: alist
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data:/opt/alist/data
    ports:
      - 5244:5244
